language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
addons:
  apt:
    packages:
    - g++
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=sklearn-sequence-classifiers
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7"
      NUMPY_VERSION="1.6.2" SCIPY_VERSION="0.11.0" CYTHON_VERSION="0.21"
      MKL_VERSION="2017.0.3" THEANO_VERSION="0.9.0" KERAS_VERSION="2.0.5"
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
      NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.17.0" CYTHON_VERSION="0.23.4"
      MKL_VERSION="2017.0.3" THEANO_VERSION="0.9.0" KERAS_VERSION="2.0.5"
    - DISTRIB="conda" PYTHON_VERSION="3.6.2" COVERAGE="true"
      NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1" CYTHON_VERSION="0.26"
      MKL_VERSION="2017.0.3" THEANO_VERSION="0.9.0" KERAS_VERSION="2.0.5"


install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
after_success: source ci_scripts/travis/success.sh
